spring.datasource.url=jdbc:h2:mem:donaciones;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.application.name=donaciones
server.port=8081
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.jackson.deserialization.fail-on-unknown-properties=false
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.datadog.metrics.export.enabled=false
management.otlp.metrics.export.enabled=false
spring.devtools.restart.enabled=false
donatrack.donadores-y-entidades.url=http://localhost:8082
donatrack.logistica.url=http://localhost:8083
