spring.datasource.url=jdbc:h2:mem:logistica;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.application.name=logistica
server.port=8083
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.jackson.deserialization.fail-on-unknown-properties=false
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.datadog.metrics.export.enabled=false
management.otlp.metrics.export.enabled=false
spring.devtools.restart.enabled=false
integrations.donadores-url=http://localhost:8082
integrations.donaciones-url=http://localhost:8081
spring.rabbitmq.addresses=amqp://guest:guest@localhost:5672
spring.rabbitmq.dynamic=false
logistica.messaging.enabled=false
app.component=logistica
app.instance-id=local-api
management.health.rabbit.enabled=false
management.metrics.distribution.percentiles-histogram.http.server.requests=true
